services:

  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./src:/var/www/html/wp-content/plugins/meu-plugin
      - ./personal-theme:/var/www/html/wp-content/themes/personal-theme

  db:
    image: mysql:8.4.3
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer:4.8.1
    restart: always
    ports:
      - 8888:8080

networks:
  back:

volumes:
  db:
